"""Added security question and answer

Revision ID: 0afa7b0725f8
Revises: 97e3743fa4db
Create Date: 2024-12-13 23:03:38.646343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0afa7b0725f8'
down_revision = '97e3743fa4db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('security_question_answer', sa.String(length=250), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('security_question_answer')

    # ### end Alembic commands ###
