"""Add encryption metadata\

Revision ID: 5aac08f8bce3
Revises: 0b7859edf35c
Create Date: 2025-02-12 21:18:44.453973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5aac08f8bce3'
down_revision = '0b7859edf35c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_metadata', schema=None) as batch_op:
        batch_op.add_column(sa.Column('encryption_metadata', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_metadata', schema=None) as batch_op:
        batch_op.drop_column('encryption_metadata')

    # ### end Alembic commands ###
